In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [52]:
df=pd.read_csv("/content/drive/MyDrive/Academic_Projects_Folder/NS/lyrics-v5.csv")
df

id                            album_title eng_album_title    album_rd  \
0      0                         2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12   
1      1                         2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12   
2      2                         2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12   
3      3                         2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12   
4      4                         2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12   
..   ...                                    ...             ...         ...   
226  226  Butter (Hotter, Sweeter, Cooler) - EP             NaN  2021-06-04   
227  227  Butter (Hotter, Sweeter, Cooler) - EP             NaN  2021-06-04   
228  228  Butter (Hotter, Sweeter, Cooler) - EP             NaN  2021-06-04   
229  229  Butter (Hotter, Sweeter, Cooler) - EP             NaN  2021-06-04   
230  230  Butter (Hotter, Sweeter, Cooler) - EP             NaN  2021-06-04   

     album_seq                          track_title kor_track_title  \
0            1  Intro: 2 Cool 4 Skool (ft. DJ Friz)             NaN   
1            2             We Are Bulletproof Pt.2              NaN   
2            3              Skit: Circle Room Talk              NaN   
3            4                       No More Dream              NaN   
4            5                            Interlude             NaN   
..         ...                                  ...             ...   
226          1                               Butter             NaN   
227          2                Butter (Hotter Remix)             NaN   
228          3               Butter (Sweeter Remix)             NaN   
229          4                Butter (Cooler Remix)             NaN   
230          5                Butter (Instrumental)             NaN   

                         eng_track_title  \
0    Intro: 2 Cool 4 Skool (ft. DJ Friz)   
1                We Are Bulletproof Pt.2   
2                 Skit: Circle Room Talk   
3                          No More Dream   
4                              Interlude   
..                                   ...   
226                               Butter   
227                Butter (Hotter Remix)   
228               Butter (Sweeter Remix)   
229                Butter (Cooler Remix)   
230                Butter (Instrumental)   

                                                lyrics  hidden_track  remix  \
0    we’re now going to progress to some steps\nwhi...         False  False   
1    (what) give it to me\n (what) be nervous\n (wh...         False  False   
2    rap monster: it was a big hit\nv: year 2006!\n...         False  False   
3    hey, what's your dream?\n hey, what’s your dre...         False  False   
4                                                  NaN         False  False   
..                                                 ...           ...    ...   
226  Smooth like butter\nLike a criminal undercover...         False  False   
227  Smooth like butter\nLike a criminal undercover...         False  False   
228  Smooth like butter\nLike a criminal undercover...         False  False   
229  Smooth like butter\nLike a criminal undercover...         False  False   
230                                                NaN         False  False   

    featured performed_by  repackaged lang  has_full_ver  
0    DJ Friz           RM       False  KOR         False  
1        NaN          BTS       False  KOR         False  
2        NaN          BTS       False  KOR         False  
3        NaN          BTS       False  KOR         False  
4        NaN          BTS       False  NaN         False  
..       ...          ...         ...  ...           ...  
226      NaN          BTS       False  ENG         False  
227      NaN          BTS       False  ENG         False  
228      NaN          BTS       False  ENG         False  
229      NaN          BTS       False  ENG         False  
230      NaN          NaN       False  NaN         False  

[231 rows x 16 co

In [53]:
df.columns

Index(['id', 'album_title', 'eng_album_title', 'album_rd', 'album_seq',
       'track_title', 'kor_track_title', 'eng_track_title', 'lyrics',
       'hidden_track', 'remix', 'featured', 'performed_by', 'repackaged',
       'lang', 'has_full_ver'],
      dtype='object')

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
features = ['id','eng_track_title','lang','album_title', 'lyrics']

In [56]:
def combine_features(row):
    return row['eng_track_title']+" "+row['lang']+" "+row['album_title']+" "+row['lyrics']

In [57]:
for feature in features:
    df[feature] = df[feature].fillna('')

In [58]:
df["combined_features"] = df.apply(combine_features,axis=1) 

In [44]:
df.head(50)

id                          album_title  \
0    0                       2 Cool 4 Skool   
1    1                       2 Cool 4 Skool   
2    2                       2 Cool 4 Skool   
3    3                       2 Cool 4 Skool   
4    4                       2 Cool 4 Skool   
5    5                       2 Cool 4 Skool   
6    6                       2 Cool 4 Skool   
7    7                       2 Cool 4 Skool   
8    8                       2 Cool 4 Skool   
9    9                            O!RUL8,2?   
10  10                            O!RUL8,2?   
11  11                            O!RUL8,2?   
12  12                            O!RUL8,2?   
13  13                            O!RUL8,2?   
14  14                            O!RUL8,2?   
15  15                            O!RUL8,2?   
16  16                            O!RUL8,2?   
17  17                            O!RUL8,2?   
18  18                            O!RUL8,2?   
19  19                     Skool Luv Affair   
20  20                     Skool Luv Affair   
21  21                     Skool Luv Affair   
22  22                     Skool Luv Affair   
23  23                     Skool Luv Affair   
24  24                     Skool Luv Affair   
25  25                     Skool Luv Affair   
26  26                     Skool Luv Affair   
27  27                     Skool Luv Affair   
28  28                     Skool Luv Affair   
29  29  Skool Luv Affair (Special Addition)   
30  30  Skool Luv Affair (Special Addition)   
31  31  Skool Luv Affair (Special Addition)   
32  32  Skool Luv Affair (Special Addition)   
33  33  Skool Luv Affair (Special Addition)   
34  34  Skool Luv Affair (Special Addition)   
35  35  Skool Luv Affair (Special Addition)   
36  36  Skool Luv Affair (Special Addition)   
37  37  Skool Luv Affair (Special Addition)   
38  38  Skool Luv Affair (Special Addition)   
39  39  Skool Luv Affair (Special Addition)   
40  40  Skool Luv Affair (Special Addition)   
41  41                        Dark and Wild   
42  42                        Dark and Wild   
43  43                        Dark and Wild   
44  44                        Dark and Wild   
45  45                        Dark and Wild   
46  46                        Dark and Wild   
47  47                        Dark and Wild   
48  48                        Dark and Wild   
49  49                        Dark and Wild   

                        eng_album_title    album_rd  album_seq  \
0                        2 Cool 4 Skool  2013-06-12          1   
1                        2 Cool 4 Skool  2013-06-12          2   
2                        2 Cool 4 Skool  2013-06-12          3   
3                        2 Cool 4 Skool  2013-06-12          4   
4                        2 Cool 4 Skool  2013-06-12          5   
5                        2 Cool 4 Skool  2013-06-12          6   
6                        2 Cool 4 Skool  2013-06-12          7   
7                        2 Cool 4 Skool  2013-06-12          8   
8                        2 Cool 4 Skool  2013-06-12          9   
9                             O!RUL8,2?  2013-09-11          1   
10                            O!RUL8,2?  2013-09-11          2   
11                            O!RUL8,2?  2013-09-11          3   
12                            O!RUL8,2?  2013-09-11          4   
13                            O!RUL8,2?  2013-09-11          5   
14                            O!RUL8,2?  2013-09-11          6   
15                            O!RUL8,2?  2013-09-11          7   
16                            O!RUL8,2?  2013-09-11          8   
17                            O!RUL8,2?  2013-09-11          9   
18                            O!RUL8,2?  2013-09-11         10   
19                     Skool Luv Affair  2014-02-12          1   
20                     Skool Luv Affair  2014-02-12          2   
21                     Skool Luv Affair  2014-02-12          3   
22                     Skool Luv Affair  2014-02-12          4   
23                    

In [59]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])

In [60]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [61]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim 

array([[1.        , 0.20331319, 0.20977755, ..., 0.26681052, 0.26681052,
        0.        ],
       [0.20331319, 1.        , 0.44300411, ..., 0.44496375, 0.44496375,
        0.        ],
       [0.20977755, 0.44300411, 1.        , ..., 0.43792405, 0.43792405,
        0.        ],
       ...,
       [0.26681052, 0.44496375, 0.43792405, ..., 1.        , 0.99961449,
        0.14398473],
       [0.26681052, 0.44496375, 0.43792405, ..., 0.99961449, 1.        ,
        0.14398473],
       [0.        , 0.        , 0.        , ..., 0.14398473, 0.14398473,
        1.        ]])

In [62]:
def get_title_from_index(id):
    return df[df.id == id]["eng_track_title"].values[0]  
def get_index_from_title(eng_track_title):
    return df[df.eng_track_title == eng_track_title]["id"].values[0]

In [64]:
song_selected = "Butter"
song_id = get_index_from_title(song_selected)

print(song_id)
similar_songs = list(enumerate(cosine_sim[song_id]))

226


In [65]:
similar_songs

[(0, 0.2671196253579725),
 (1, 0.445479249367826),
 (2, 0.43843139676096954),
 (3, 0.3301465642213103),
 (4, 0.022697981217836883),
 (5, 0.46891139923880143),
 (6, 0.475977986998168),
 (7, 0.36963931898543073),
 (8, 0.41217011907592477),
 (9, 0.37089623376556474),
 (10, 0.42244721978405597),
 (11, 0.44652355122354626),
 (12, 0.47568982218427486),
 (13, 0.37951905745769593),
 (14, 0.4333692603329136),
 (15, 0.5064619668533213),
 (16, 0.46111590735585284),
 (17, 0.42727558600215765),
 (18, 0.309757749309791),
 (19, 0.5195207191379526),
 (20, 0.4718893402550514),
 (21, 0.0),
 (22, 0.4606428805038873),
 (23, 0.3984290796661474),
 (24, 0.4729788306018651),
 (25, 0.5293353020170457),
 (26, 0.26767371844116317),
 (27, 0.3383955416146389),
 (28, 0.4892950269141201),
 (29, 0.5098716388454236),
 (30, 0.46183570242710476),
 (31, 0.5207081536694331),
 (32, 0.471830629294917),
 (33, 0.0),
 (34, 0.46054652177874483),
 (35, 0.39838550454930405),
 (36, 0.4728427019961957),
 (37, 0.5292760027055934),
 

In [66]:
sorted_similar_songs = sorted(similar_songs,key=lambda x:x[1],reverse=True)[1:]
sorted_similar_songs

[(228, 0.9996147186849097),
 (229, 0.9996147186849097),
 (227, 0.9980673339391333),
 (70, 0.5893212382511714),
 (41, 0.5785243243817583),
 (163, 0.5716250529110163),
 (188, 0.5713718529824487),
 (181, 0.5712665794941333),
 (150, 0.5704383815721585),
 (186, 0.5630629314027024),
 (178, 0.5625184206004973),
 (146, 0.554269769120591),
 (168, 0.554269769120591),
 (223, 0.5438010638897712),
 (47, 0.5399315570257224),
 (71, 0.5383452770506503),
 (76, 0.5379610465563001),
 (115, 0.5311404371985098),
 (25, 0.5293353020170457),
 (37, 0.5292760027055934),
 (100, 0.5277275874525286),
 (116, 0.5232976034199848),
 (101, 0.523115613612316),
 (138, 0.5231031590590998),
 (31, 0.5207081536694331),
 (131, 0.5201222331347509),
 (169, 0.5201222331347509),
 (19, 0.5195207191379526),
 (182, 0.5165509908968657),
 (185, 0.5146676034595645),
 (151, 0.5121789763160248),
 (144, 0.5118432446744334),
 (29, 0.5098716388454236),
 (137, 0.5079372147458479),
 (15, 0.5064619668533213),
 (128, 0.5053105735060742),
 (143,

In [67]:
i=0
print("Top 5 similar songs to "+song_selected+" are:\n")
for element in sorted_similar_songs:
    #print(element)
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar songs to Butter are:

Butter (Sweeter Remix)
Butter (Cooler Remix)
Butter (Hotter Remix)
Skit: One Night in a Strange City 
Intro: What Am I to You? 
Tear
