In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv("lyrics-v5.csv")
df

id     album_title eng_album_title    album_rd  album_seq  \
0   0  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          1   
1   1  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          2   
2   2  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          3   
3   3  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          4   
4   4  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          5   

                           track_title kor_track_title  \
0  Intro: 2 Cool 4 Skool (ft. DJ Friz)             NaN   
1             We Are Bulletproof Pt.2              NaN   
2              Skit: Circle Room Talk              NaN   
3                       No More Dream              NaN   
4                            Interlude             NaN   

                       eng_track_title  \
0  Intro: 2 Cool 4 Skool (ft. DJ Friz)   
1              We Are Bulletproof Pt.2   
2               Skit: Circle Room Talk   
3                        No More Dream   
4                            Interlude   

                                              lyrics  hidden_track  remix  \
0  we’re now going to progress to some steps\nwhi...         False  False   
1  (what) give it to me\n (what) be nervous\n (wh...         False  False   
2  rap monster: it was a big hit\nv: year 2006!\n...         False  False   
3  hey, what's your dream?\n hey, what’s your dre...         False  False   
4                                                NaN         False  False   

  featured performed_by  repackaged lang  has_full_ver  
0  DJ Friz           RM       False  KOR         False  
1      NaN          BTS       False  KOR         False  
2      NaN          BTS       False  KOR         False  
3      NaN          BTS       False  KOR         False  
4      NaN          BTS       False  NaN         False

In [ ]:
df.columns

Index(['id', 'album_title', 'eng_album_title', 'album_rd', 'album_seq',
       'track_title', 'kor_track_title', 'eng_track_title', 'lyrics',
       'hidden_track', 'remix', 'featured', 'performed_by', 'repackaged',
       'lang', 'has_full_ver'],
      dtype='object')

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
features = ['id','eng_track_title','lang','album_title', 'lyrics']

In [ ]:
def combine_features(row):
    return row['eng_track_title']+" "+row['lang']+" "+row['album_title']+" "+row['lyrics']

In [ ]:
for feature in features:
    df[feature] = df[feature].fillna('')

In [ ]:
df["combined_features"] = df.apply(combine_features,axis=1) 

In [ ]:
df.head()

id     album_title eng_album_title    album_rd  album_seq  \
0   0  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          1   
1   1  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          2   
2   2  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          3   
3   3  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          4   
4   4  2 Cool 4 Skool  2 Cool 4 Skool  2013-06-12          5   

                           track_title kor_track_title  \
0  Intro: 2 Cool 4 Skool (ft. DJ Friz)             NaN   
1             We Are Bulletproof Pt.2              NaN   
2              Skit: Circle Room Talk              NaN   
3                       No More Dream              NaN   
4                            Interlude             NaN   

                       eng_track_title  \
0  Intro: 2 Cool 4 Skool (ft. DJ Friz)   
1              We Are Bulletproof Pt.2   
2               Skit: Circle Room Talk   
3                        No More Dream   
4                            Interlude   

                                              lyrics  hidden_track  remix  \
0  we’re now going to progress to some steps\nwhi...         False  False   
1  (what) give it to me\n (what) be nervous\n (wh...         False  False   
2  rap monster: it was a big hit\nv: year 2006!\n...         False  False   
3  hey, what's your dream?\n hey, what’s your dre...         False  False   
4                                                            False  False   

  featured performed_by  repackaged lang  has_full_ver  \
0  DJ Friz           RM       False  KOR         False   
1      NaN          BTS       False  KOR         False   
2      NaN          BTS       False  KOR         False   
3      NaN          BTS       False  KOR         False   
4      NaN          BTS       False              False   

                                   combined_features  
0  Intro: 2 Cool 4 Skool (ft. DJ Friz) KOR 2 Cool...  
1  We Are Bulletproof Pt.2 KOR 2 Cool 4 Skool (wh...  
2  Skit: Circle Room Talk KOR 2 Cool 4 Skool rap ...  
3  No More Dream KOR 2 Cool 4 Skool hey, what's y...  
4                         Interlude  2 Cool 4 Skool

In [ ]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])

In [ ]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim 

array([[1.        , 0.20331319, 0.20977755, ..., 0.26681052, 0.26681052,
        0.        ],
       [0.20331319, 1.        , 0.44300411, ..., 0.44496375, 0.44496375,
        0.        ],
       [0.20977755, 0.44300411, 1.        , ..., 0.43792405, 0.43792405,
        0.        ],
       ...,
       [0.26681052, 0.44496375, 0.43792405, ..., 1.        , 0.99961449,
        0.14398473],
       [0.26681052, 0.44496375, 0.43792405, ..., 0.99961449, 1.        ,
        0.14398473],
       [0.        , 0.        , 0.        , ..., 0.14398473, 0.14398473,
        1.        ]])

In [ ]:
def get_title_from_index(id):
    return df[df.id == id]["eng_track_title"].values[0]  
def get_index_from_title(eng_track_title):
    return df[df.eng_track_title == eng_track_title]["id"].values[0]

In [ ]:
song_selected = "No More Dream"
song_id = get_index_from_title(song_selected)

print(song_id)
similar_songs = list(enumerate(cosine_sim[song_id]))

3


In [ ]:
similar_songs

[(0, 0.15803210654232525),
 (1, 0.2885114635678551),
 (2, 0.3623921805510501),
 (3, 0.9999999999999984),
 (4, 0.015367348185252473),
 (5, 0.40170518618726325),
 (6, 0.39161831537498737),
 (7, 0.26177100783565466),
 (8, 0.33086450646425397),
 (9, 0.4105686838088863),
 (10, 0.26340437345852996),
 (11, 0.3188386679619801),
 (12, 0.3206490217311769),
 (13, 0.24693233529057868),
 (14, 0.31967392027717995),
 (15, 0.3863985489045554),
 (16, 0.35551828439020694),
 (17, 0.4116689897712878),
 (18, 0.2272352534558073),
 (19, 0.4038138672929835),
 (20, 0.5025372652848529),
 (21, 0.010866356110646808),
 (22, 0.4680001655245237),
 (23, 0.37122051619685414),
 (24, 0.46655998530463283),
 (25, 0.4572713230043406),
 (26, 0.6140625554656467),
 (27, 0.24939201202105693),
 (28, 0.3976770189379697),
 (29, 0.47766595809782497),
 (30, 0.40089276451309236),
 (31, 0.4070142027746101),
 (32, 0.5024747412080591),
 (33, 0.009410540438388402),
 (34, 0.4679022677793832),
 (35, 0.37117991680741824),
 (36, 0.466425704

In [ ]:
sorted_similar_songs = sorted(similar_songs,key=lambda x:x[1],reverse=True)[1:]
sorted_similar_songs

[(26, 0.6140625554656467),
 (38, 0.6140183034888326),
 (43, 0.6109884121055783),
 (182, 0.5899442262277113),
 (144, 0.5516330858241892),
 (49, 0.5341843284074156),
 (41, 0.5062168307151049),
 (20, 0.5025372652848529),
 (32, 0.5024747412080591),
 (133, 0.4951524314929442),
 (123, 0.4822972496738286),
 (108, 0.482157761282062),
 (80, 0.4795563144044901),
 (68, 0.47950301870915624),
 (142, 0.4784874022282834),
 (161, 0.4784874022282834),
 (29, 0.47766595809782497),
 (201, 0.4775572910362255),
 (193, 0.47232583284935653),
 (70, 0.4704528245979814),
 (42, 0.46871138430240705),
 (22, 0.4680001655245237),
 (34, 0.4679022677793832),
 (24, 0.46655998530463283),
 (36, 0.466425704114543),
 (137, 0.46576342486668726),
 (131, 0.4649603454441856),
 (169, 0.4649603454441856),
 (146, 0.4607629329676602),
 (168, 0.4607629329676602),
 (127, 0.4606610687752272),
 (143, 0.4595375478333913),
 (25, 0.4572713230043406),
 (176, 0.45727114477718556),
 (37, 0.4572200967315081),
 (125, 0.45166472773256044),
 (16

In [ ]:
i=0
print("Top 5 similar songs to "+song_selected+" are:\n")
for element in sorted_similar_songs:
    #print(element)
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar songs to No More Dream are:

Spine Breaker
Spine Breaker
War of Hormone 
HOME 
Paradise
Could You Turn Off Your Cell Phone? 
